services:
  dev:
    build:
      context: .
      target: debian-php82
    tty: true
    volumes:
      - dev:/home/dev/
      - /home/${USER}/.ssh:/home/dev/.ssh/
    ports:
      - "22:22"
volumes:
  dev:
