name: Build and push formatter-ci
on:
  push:
    branches: ['main']
    paths: ['ci/**']
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push formatter-ci
        uses: docker/build-push-action@v5.3.0
        with:
          context: "{{defaultContext}}:ci"
          push: true
          tags: alanfzf/php-ci-formatter:latest
          target: ci-formatter
