name: Build and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Debian base image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./debian/
          file: Dockerfile
          push: true
          tags: alanfzf/devcontainer:debian
          target: debian

      - name: Build and push Debian PHP 7.4 image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./debian/
          file: Dockerfile
          push: true
          tags: alanfzf/devcontainer:debian-php74
          target: debian-php74
